source :rubygems
gem 'httparty'
gem 'rake', '0.8.7'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'crack'
gem 'pry'
gem 'pry-rails'
gem 'pry-doc'
gem 'Url2Yml'
gem 'rspec-core'
gem 'rspec-mocks'
gem 'rspec-expectations'
gem 'activesupport'
